# Generated by Django 2.2.12 on 2020-08-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin_tracker', '0002_vitamin_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitamin',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
